In [ ]:
import os

ds_name = "ml-latest-small" #"lfm360k"
flag_case = 'promote'
embedding_method = "llama3" #"sentence_transformer" #"OpenAI" #"llama3"  #sentence_transformer #all

upload_to_git = True
os.environ["OPENAI_API_KEY"] = api_key

In [ ]:
!pip install openai==0.28.0 tqdm

Collecting openai==0.28.0
  Downloading openai-0.28.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.11/dist-packages (from openai==0.28.0) (2.32.3)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from openai==0.28.0) (3.11.12)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->openai==0.28.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->openai==0.28.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->openai==0.28.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->openai==0.28.0) (2025.1.31)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->openai==0.28.0) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->openai==0.28.0) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->openai==0.28.0) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->openai==0.28.0) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->openai==0.28.0) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->openai==0.28.0) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->openai==0.28.0) (1.18.3)
Downloading openai-0.28.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.5/76.5 kB 6.0 MB/s eta 0:00:00
Installing collected packages: openai
  Attempting uninstall: openai
    Found existing installation: openai 1.61.1
    Uninstalling openai-1.61.1:
      Successfully uninstalled openai-1.61.1
Successfully installed openai-0.28.0

In [ ]:
import os
import requests
import pandas as pd

scenario = flag_case

# Define URL mapping
file_urls = {
    ('ml-latest-small', 'promote'): "https://github.com/yasdel/Poison-RAG-Plus/raw/main/AttackData/Augmentation_Attack_Data/augmented_items_ml_latest_small_promote_sample_size_10percent.csv.gz",
    ('ml-latest-small', 'demote'): "https://github.com/yasdel/Poison-RAG-Plus/raw/main/AttackData/Augmentation_Attack_Data/augmented_items_ml_latest_small_demote_sample_size_10percent.csv.gz",
    ('lfm360k', 'promote'): "https://github.com/yasdel/Poison-RAG-Plus/raw/main/AttackData/Augmentation_Attack_Data/augmented_items_lfm360k_promote_sample_size_10percent.csv.gz",
    ('lfm360k', 'demote'): "https://github.com/yasdel/Poison-RAG-Plus/raw/main/AttackData/Augmentation_Attack_Data/augmented_items_lfm360k_demote_sample_size_10percent.csv.gz"
}

# Check if the key exists in the mapping
file_url = file_urls.get((ds_name, scenario))

if file_url:
    file_name = file_url.split("/")[-1]
    print(f"Downloading {file_name} from {file_url} ...")
    response = requests.get(file_url, stream=True)

    if response.status_code == 200:
        with open(file_name, 'wb') as file:
            for chunk in response.iter_content(chunk_size=1024):
                file.write(chunk)
        print(f"Download complete: {file_name}")

        # Load the file into a pandas DataFrame
        df_final = pd.read_csv(file_name, compression='gzip')
        print("Displaying first few rows of the dataset:")
        display(df_final)
    else:
        print(f"Failed to download {file_name}. HTTP Status Code: {response.status_code}")
else:
    print("Invalid dataset or scenario selection.")

Downloading augmented_items_ml_latest_small_promote_sample_size_10percent.csv.gz from https://github.com/yasdel/Poison-RAG-Plus/raw/main/AttackData/Augmentation_Attack_Data/augmented_items_ml_latest_small_promote_sample_size_10percent.csv.gz ...
Download complete: augmented_items_ml_latest_small_promote_sample_size_10percent.csv.gz
Displaying first few rows of the dataset:

,itemId,title,genres,tag,enriched_description,pop_class,sim_items_200,sim_items_200_class_based,phase1_10p_promote_emotional,phase1_10p_promote_neighbor5,...,final_text_phase1_10p_promote_neighbor15,final_text_phase1_10p_promote_chain15,final_text_phase1_10p_promote_trigger15,final_text_phase1_40p_promote_emotional,final_text_phase1_40p_promote_neighbor5,final_text_phase1_40p_promote_chain5,final_text_phase1_40p_promote_trigger5,final_text_phase1_40p_promote_neighbor15,final_text_phase1_40p_promote_chain15,final_text_phase1_40p_promote_trigger15
0,7,Sabrina (1995),Comedy|Romance,['remake'],**Sabrina (1995)** is a delightful romantic co...,0,"[915, 360, 6899, 345, 2155, 295, 68, 287, 1549...","{0: [186, 500, 555, 597, 1197, 1569, 1777, 229...",NaN,NaN,...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...
1,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,[],**Money Train (1995)** is a thrilling blend of...,1,"[1604, 5454, 124859, 3537, 2391, 3384, 2344, 4...","{0: [1, 21, 172, 296, 333, 434, 778, 1073, 122...",NaN,NaN,...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...
2,36,Dead Man Walking (1995),Crime|Drama,"['death penalty', 'Nun']",**Dead Man Walking (1995)** is a poignant and ...,0,"[726, 7883, 81, 54787, 4160, 336, 1114, 3258, ...","{0: [151, 253, 282, 288, 377, 587, 1246, 1923,...",NaN,NaN,...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...
3,17,Sense and Sensibility (1995),Drama|Romance,['Jane Austen'],**Sense and Sensibility (1995)** is a beautifu...,0,"[7669, 28, 26958, 40629, 70521, 2027, 46976, 1...","{0: [34, 236, 261, 357, 497, 500, 509, 1674, 2...",NaN,NaN,...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...
4,3,Grumpier Old Men (1995),Comedy|Romance,"['moldy', 'old']",**Grumpier Old Men (1995)** is a delightful se...,0,"[3450, 1179, 184349, 1929, 100083, 3258, 1473,...","{0: [357, 410, 1278, 1721, 2003, 2324, 2407, 4...",NaN,NaN,...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1601,190221,Hommage à Zgougou (et salut à Sabine Mamou) (2...,Documentary,[],**Hommage à Zgougou (et salut à Sabine Mamou) ...,2,"[1933, 773, 166015, 4449, 2075, 5537, 100106, ...","{0: [1204, 2324, 2617, 4973, 5995], 1: [1131, ...",NaN,NaN,...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...
1602,190207,Tilt (2011),Drama|Romance,[],**Tilt (2011)** is a poignant drama that intri...,2,"[52724, 131480, 82053, 2231, 58803, 100083, 80...","{0: [16, 357, 1625, 1721, 2915, 8949, 49272], ...",NaN,NaN,...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...
1603,190219,Bunny (1998),Animation,[],**Bunny (1998)** is a captivating animated sho...,2,"[183301, 2624, 134095, 153070, 27664, 82767, 3...","{0: [596, 1022, 1032, 2294, 2321, 2324, 2407, ...",NaN,NaN,...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...
1604,189043,Boundaries (2018),Comedy|Drama,[],**Boundaries (2018)** is a heartwarming blend ...,2,"[6886, 32584, 161032, 3497, 8380, 99415, 2766,...","{0: [186, 762, 3471, 3948, 5377, 8784, 8949], ...",NaN,NaN,...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...
1605,190213,John From (2015),Drama,[],**John From (2015)** is a poignant and evocati...,2,"[144478, 8183, 6111, 7285, 4074, 2915, 7767, 1...","{0: [2324, 2580, 2915, 5377], 1: [29, 58, 175,...",NaN,NaN,...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...

In [ ]:
import os
import io
import gzip
import pandas as pd
from google.colab import files

# Step 2: Function to load files
def load_file(file_name):
    """
    Load a file as a DataFrame.
    Handles .csv and .csv.gz files with retries for encoding errors.
    """
    is_gzip = file_name.endswith('.gz')  # Check file type
    encodings = ['utf-8', 'latin1', 'ISO-8859-1']  # Encodings to try

    for encoding in encodings:
        try:
            if is_gzip:
                print(f"Attempting to load gzip file with encoding: {encoding}")
                with gzip.open(file_name, 'rt', encoding=encoding) as f:
                    df = pd.read_csv(f)
            else:
                print(f"Attempting to load CSV file with encoding: {encoding}")
                df = pd.read_csv(file_name, encoding=encoding)

            print("File loaded successfully!")
            return df
        except UnicodeDecodeError as e:
            print(f"Encoding error with {encoding}: {e}. Retrying with a different encoding...")
        except Exception as e:
            print(f"Unexpected error: {e}")

    # If all attempts fail
    raise ValueError("Unable to load the file with the provided encodings.")

# Step 3: Upload and load the first file (Promote)
print("\nUpload the file for 'phase1_promote_applied == True'")
#uploaded_promote = files.upload()
#file_name = list(uploaded_promote.keys())[0]
#df_loaded = load_file(file_name)

#if flag_case == 'promote':
#  df_final = df_loaded.loc[df_loaded[f'phase1_{flag_case}_applied'] == True]
#elif flag_case == 'demote':
#  df_final = df_loaded.loc[df_loaded[f'phase1_{flag_case}_applied'] == True]
#display(df_final)

Upload the file for 'phase1_promote_applied == True'

In [ ]:
############################################
# B) Sentence Transformers Embedding Example
############################################
import os
import io
import gzip
import pandas as pd

#df = df_final.sample(n=10, random_state=42)
#df = df.reset_index(drop=True)

df = df_final.copy()
display(df)

# 3. DEFINE YOUR EMBEDDING COLUMNS

# Select columns that start with 'final_text' and add 'enriched_description'
embedding_columns = [col for col in df.columns if col.startswith('final_text')]
embedding_columns.append('enriched_description')

# Output
print("Promote Embedding Columns:")
print(embedding_columns)

,itemId,title,genres,tag,enriched_description,pop_class,sim_items_200,sim_items_200_class_based,phase1_10p_promote_emotional,phase1_10p_promote_neighbor5,...,final_text_phase1_10p_promote_neighbor15,final_text_phase1_10p_promote_chain15,final_text_phase1_10p_promote_trigger15,final_text_phase1_40p_promote_emotional,final_text_phase1_40p_promote_neighbor5,final_text_phase1_40p_promote_chain5,final_text_phase1_40p_promote_trigger5,final_text_phase1_40p_promote_neighbor15,final_text_phase1_40p_promote_chain15,final_text_phase1_40p_promote_trigger15
0,7,Sabrina (1995),Comedy|Romance,['remake'],**Sabrina (1995)** is a delightful romantic co...,0,"[915, 360, 6899, 345, 2155, 295, 68, 287, 1549...","{0: [186, 500, 555, 597, 1197, 1569, 1777, 229...",NaN,NaN,...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...
1,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,[],**Money Train (1995)** is a thrilling blend of...,1,"[1604, 5454, 124859, 3537, 2391, 3384, 2344, 4...","{0: [1, 21, 172, 296, 333, 434, 778, 1073, 122...",NaN,NaN,...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...
2,36,Dead Man Walking (1995),Crime|Drama,"['death penalty', 'Nun']",**Dead Man Walking (1995)** is a poignant and ...,0,"[726, 7883, 81, 54787, 4160, 336, 1114, 3258, ...","{0: [151, 253, 282, 288, 377, 587, 1246, 1923,...",NaN,NaN,...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...
3,17,Sense and Sensibility (1995),Drama|Romance,['Jane Austen'],**Sense and Sensibility (1995)** is a beautifu...,0,"[7669, 28, 26958, 40629, 70521, 2027, 46976, 1...","{0: [34, 236, 261, 357, 497, 500, 509, 1674, 2...",NaN,NaN,...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...
4,3,Grumpier Old Men (1995),Comedy|Romance,"['moldy', 'old']",**Grumpier Old Men (1995)** is a delightful se...,0,"[3450, 1179, 184349, 1929, 100083, 3258, 1473,...","{0: [357, 410, 1278, 1721, 2003, 2324, 2407, 4...",NaN,NaN,...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1601,190221,Hommage à Zgougou (et salut à Sabine Mamou) (2...,Documentary,[],**Hommage à Zgougou (et salut à Sabine Mamou) ...,2,"[1933, 773, 166015, 4449, 2075, 5537, 100106, ...","{0: [1204, 2324, 2617, 4973, 5995], 1: [1131, ...",NaN,NaN,...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...,**Hommage à Zgougou (et salut à Sabine Mamou) ...
1602,190207,Tilt (2011),Drama|Romance,[],**Tilt (2011)** is a poignant drama that intri...,2,"[52724, 131480, 82053, 2231, 58803, 100083, 80...","{0: [16, 357, 1625, 1721, 2915, 8949, 49272], ...",NaN,NaN,...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...,**Tilt (2011)** is a poignant drama that intri...
1603,190219,Bunny (1998),Animation,[],**Bunny (1998)** is a captivating animated sho...,2,"[183301, 2624, 134095, 153070, 27664, 82767, 3...","{0: [596, 1022, 1032, 2294, 2321, 2324, 2407, ...",NaN,NaN,...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...,**Bunny (1998)** is a captivating animated sho...
1604,189043,Boundaries (2018),Comedy|Drama,[],**Boundaries (2018)** is a heartwarming blend ...,2,"[6886, 32584, 161032, 3497, 8380, 99415, 2766,...","{0: [186, 762, 3471, 3948, 5377, 8784, 8949], ...",NaN,NaN,...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...,**Boundaries (2018)** is a heartwarming blend ...
1605,190213,John From (2015),Drama,[],**John From (2015)** is a poignant and evocati...,2,"[144478, 8183, 6111, 7285, 4074, 2915, 7767, 1...","{0: [2324, 2580, 2915, 5377], 1: [29, 58, 175,...",NaN,NaN,...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...,**John From (2015)** is a poignant and evocati...

Promote Embedding Columns:
['final_text_phase1_10p_promote_emotional', 'final_text_phase1_10p_promote_neighbor5', 'final_text_phase1_10p_promote_chain5', 'final_text_phase1_10p_promote_trigger5', 'final_text_phase1_10p_promote_neighbor15', 'final_text_phase1_10p_promote_chain15', 'final_text_phase1_10p_promote_trigger15', 'final_text_phase1_40p_promote_emotional', 'final_text_phase1_40p_promote_neighbor5', 'final_text_phase1_40p_promote_chain5', 'final_text_phase1_40p_promote_trigger5', 'final_text_phase1_40p_promote_neighbor15', 'final_text_phase1_40p_promote_chain15', 'final_text_phase1_40p_promote_trigger15', 'enriched_description']

In [ ]:
####################################
# A) OpenAI Embedding Extraction
####################################
import os
import io
import gzip
import math
import random
import time
import pandas as pd
import concurrent.futures
from tqdm import tqdm
from typing import List, Optional
from google.colab import files
import openai
import shutil

openai.api_key = os.getenv("OPENAI_API_KEY")  # Or manually set: openai.api_key = "your-key"



# 5. HELPER FUNCTIONS

def create_combined_text(row, column_name: str) -> str:
    """
    Combine title, genres, and column text (tags) into a single string.
    """
    title = row.get('title', '')
    genre = row.get('genres', '').replace('|', ' ') if 'genres' in row else ''
    tags = row.get(column_name, [])
    if isinstance(tags, str):
        try:
            tags = eval(tags)  # if it's a string of list-likes
        except:
            pass
    tags_str = ' '.join(tags) if isinstance(tags, list) else str(tags)
    return f"{title} {genre} {tags_str}"

def generate_openai_embedding(text: str, model: str = "text-embedding-ada-002") -> Optional[List[float]]:
    """
    Generate a single embedding from OpenAI's API.
    """
    if not text.strip():
        return []
    try:
        response = openai.Embedding.create(input=text, model=model)
        embedding = response['data'][0]['embedding']
        # Small random pause to reduce risk of hitting rate limits
        time.sleep(random.uniform(0.3, 0.5))
        return embedding
    except Exception as e:
        print(f"Error generating embedding for text: {text[:50]}... \nError: {e}")
        return []

def get_openai_embeddings_parallel(texts: List[str], max_workers: int = 10) -> List[List[float]]:
    """
    Generate embeddings for a list of texts using ThreadPoolExecutor.
    """
    embeddings = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_text = {executor.submit(generate_openai_embedding, txt): txt for txt in texts}
        for future in tqdm(concurrent.futures.as_completed(future_to_text),
                           total=len(texts), desc="Generating OpenAI Embeddings"):
            emb = future.result()
            embeddings.append(emb)
    return embeddings

def estimate_chunk_size(df: pd.DataFrame, sample_size: int = 1000, max_size_mb: int = 25) -> int:
    """
    Estimate how many rows per chunk to keep each file ~25MB max when gzipped.
    """
    max_size_bytes = max_size_mb * 1024 * 1024
    sample = df.head(sample_size)
    csv_buffer = io.StringIO()
    sample.to_csv(csv_buffer, index=False)
    sample_size_bytes = len(csv_buffer.getvalue().encode('utf-8'))
    avg_size_per_row = sample_size_bytes / max(1, len(sample))
    estimated_rows = max(1, math.floor(max_size_bytes / avg_size_per_row))
    return estimated_rows

def split_dataframe(df: pd.DataFrame, chunk_size: int):
    """
    Split the DataFrame into multiple DataFrames each up to 'chunk_size' rows.
    """
    num_chunks = math.ceil(len(df) / chunk_size)
    return [df.iloc[i*chunk_size:(i+1)*chunk_size] for i in range(num_chunks)]

# 6. RUN THE OPENAI EMBEDDING EXTRACTION
max_workers = 12
output_dir = f"openai_embeddings_attacked_ds_name_{ds_name}_{flag_case}"
os.makedirs(output_dir, exist_ok=True)

if embedding_method.lower() == 'openai':
  for column in embedding_columns:
      print(f"\nProcessing embeddings for column: {column}")

      # Create combined text
      df[f'combined_{column}'] = df.apply(lambda row: create_combined_text(row, column), axis=1)
      texts = df[f'combined_{column}'].tolist()

      # Generate embeddings in parallel
      embeddings = get_openai_embeddings_parallel(texts, max_workers=max_workers)

      # Build a DataFrame to store embeddings
      embedding_df = pd.DataFrame({
          'itemId': df['itemId'],
          'embeddings': embeddings
      })

      # Convert vectors to space-separated strings
      embedding_df['embeddings'] = embedding_df['embeddings'].apply(lambda x: ' '.join(map(str, x)) if x else '')

      # Shuffle rows for random distribution
      embedding_df = embedding_df.sample(frac=1, random_state=42).reset_index(drop=True)

      # Split into chunks
      chunk_size = estimate_chunk_size(embedding_df, sample_size=1000, max_size_mb=25)
      chunks = split_dataframe(embedding_df, chunk_size)

      # Save each chunk
      for idx, chunk in enumerate(chunks):
          output_file = os.path.join(output_dir, f"openai_{column}_part{idx+1}.csv.gz")
          with gzip.open(output_file, 'wt', encoding='utf-8') as f:
              chunk.to_csv(f, index=False)
          print(f"Saved: {output_file}")

  print("\nOpenAI Embedding Extraction Complete!")


  # Zip and download the folder
  zip_file_name = f"{output_dir}.zip"
  shutil.make_archive(output_dir, 'zip', output_dir)
  files.download(zip_file_name)

In [ ]:
if embedding_method.lower() == 'sentence_transformer':
  !pip install --quiet sentence-transformers tqdm
  import math
  import concurrent.futures
  from tqdm import tqdm
  from sentence_transformers import SentenceTransformer
  import shutil

  # 4. LOAD MODEL
  model_name = 'all-MiniLM-L12-v2'
  sentence_model = SentenceTransformer(model_name)

# 5. HELPER FUNCTIONS
def create_combined_text(row, column_name: str) -> str:
    """
    Combine title, genres, and column text (tags) into a single string.
    """
    title = row.get('title', '')
    genre = row.get('genres', '').replace('|', ' ') if 'genres' in row else ''
    tags = row.get(column_name, [])
    if isinstance(tags, str):
        try:
            tags = eval(tags)  # if it's a string of list-likes
        except:
            pass
    tags_str = ' '.join(tags) if isinstance(tags, list) else str(tags)
    return f"{title} {genre} {tags_str}"

def get_batch_embeddings(batch_texts):
    return sentence_model.encode(batch_texts, show_progress_bar=False).tolist()

def estimate_chunk_size(df: pd.DataFrame, sample_size: int = 1000, max_size_mb: int = 25) -> int:
    max_size_bytes = max_size_mb * 1024 * 1024
    sample = df.head(sample_size)
    csv_buffer = io.StringIO()
    sample.to_csv(csv_buffer, index=False)
    sample_size_bytes = len(csv_buffer.getvalue().encode('utf-8'))
    avg_size_per_row = sample_size_bytes / max(1, len(sample))
    return max(1, math.floor(max_size_bytes / avg_size_per_row))

def split_dataframe(df: pd.DataFrame, chunk_size: int):
    num_chunks = math.ceil(len(df) / chunk_size)
    return [df.iloc[i*chunk_size:(i+1)*chunk_size] for i in range(num_chunks)]

# 6. RUN THE SENTENCE TRANSFORMERS EMBEDDING EXTRACTION
max_workers = 10
batch_size = 64
output_dir = f"sentence_transformer_embeddings_output_ds_name_{ds_name}_{flag_case}"
os.makedirs(output_dir, exist_ok=True)

if embedding_method.lower() == 'sentence_transformer':
  for column in embedding_columns:
      print(f"\nProcessing embeddings for column: {column}")

      # Create combined text
      df[f'combined_{column}'] = df.apply(lambda row: create_combined_text(row, column), axis=1)
      texts = df[f'combined_{column}'].tolist()

      # Split texts into batches
      batches = [texts[i:i+batch_size] for i in range(0, len(texts), batch_size)]

      # Generate embeddings in parallel
      embeddings = []
      with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
          futures = [executor.submit(get_batch_embeddings, batch) for batch in batches]
          for future in tqdm(concurrent.futures.as_completed(futures),
                            total=len(futures), desc="Generating SentenceTransformer Embeddings"):
              embeddings.extend(future.result())

      # Prepare final DataFrame
      embedding_df = pd.DataFrame({
          'itemId': df['itemId'],
          'embeddings': embeddings
      })
      embedding_df['embeddings'] = embedding_df['embeddings'].apply(lambda x: ' '.join(map(str, x)) if x else '')
      embedding_df = embedding_df.sample(frac=1, random_state=42).reset_index(drop=True)

      # Split and save
      chunk_size = estimate_chunk_size(embedding_df, sample_size=1000, max_size_mb=25)
      chunks = split_dataframe(embedding_df, chunk_size)
      for idx, chunk in enumerate(chunks):
          output_file = os.path.join(output_dir, f"st_{column}_part{idx+1}.csv.gz")
          with gzip.open(output_file, 'wt', encoding='utf-8') as f:
              chunk.to_csv(f, index=False)
          print(f"Saved: {output_file}")

  print("\nSentence Transformers Embedding Extraction Complete!")


  # Zip and download the folder
  zip_file_name = f"{output_dir}.zip"
  shutil.make_archive(output_dir, 'zip', output_dir)
  files.download(zip_file_name)

In [ ]:
if embedding_method.lower() == 'llama3':
  #################################################
  # C) Llama Embedding Extraction (Hugging Face)
  #################################################
  !pip install --quiet transformers accelerate bitsandbytes huggingface_hub
  import os
  import io
  import gzip
  import math
  import torch
  import pandas as pd
  import concurrent.futures
  from tqdm import tqdm
  from transformers import AutoTokenizer, AutoModelForCausalLM
  from huggingface_hub import login
  from google.colab import files
  import shutil

  # 1. GPU/CPU selection
  device = "cuda" if torch.cuda.is_available() else "cpu"
  model_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

  # 2. OPTIONAL: Rename Columns or Inspect
  if 'artist' in df.columns:
      df.rename(columns={'artist': 'title'}, inplace=True)
  print("Dataframe columns:", df.columns)
  display(df.head())

  login(hf_token)

  model_name = "meta-llama/Llama-2-7b-hf"  # Example Llama2 model name
  tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=hf_token)

  # Use 'device_map="auto"' only if using a GPU; otherwise None
  model = AutoModelForCausalLM.from_pretrained(
      model_name,
      device_map="auto" if torch.cuda.is_available() else None,
      torch_dtype=model_dtype,
      use_auth_token=hf_token
  )
  model.eval()  # Put model in evaluation mode

# 5. HELPER FUNCTIONS
def create_combined_text(row, column_name: str) -> str:
    title = row.get('title', '')
    genre = row.get('genres', '').replace('|', ' ') if 'genres' in row else ''
    tags = row.get(column_name, [])
    if isinstance(tags, str):
        try:
            tags = eval(tags)
        except:
            pass
    tags_str = ' '.join(tags) if isinstance(tags, list) else str(tags)
    return f"{title} {genre} {tags_str}"

def get_llama_embeddings(batch_texts):
    """
    Embeds a batch of texts using Llama model's last hidden state (mean-pooled).
    """
    if tokenizer.pad_token is None:
        # Some Llama-based models might not have a pad token
        tokenizer.pad_token = tokenizer.eos_token
        model.resize_token_embeddings(len(tokenizer))

    inputs = tokenizer(
        batch_texts,
        return_tensors="pt",
        padding=True,
        truncation=True
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=True)
        last_hidden = outputs.hidden_states[-1]  # Final layer
        embeddings = last_hidden.mean(dim=1)

    return embeddings.cpu().numpy().tolist()

def estimate_chunk_size(df: pd.DataFrame, sample_size: int = 1000, max_size_mb: int = 25) -> int:
    max_size_bytes = max_size_mb * 1024 * 1024
    sample = df.head(sample_size)
    csv_buffer = io.StringIO()
    sample.to_csv(csv_buffer, index=False)
    sample_size_bytes = len(csv_buffer.getvalue().encode('utf-8'))
    avg_size_per_row = sample_size_bytes / max(1, len(sample))
    return max(1, math.floor(max_size_bytes / avg_size_per_row))

def split_dataframe(df: pd.DataFrame, chunk_size: int):
    num_chunks = math.ceil(len(df) / chunk_size)
    return [df.iloc[i*chunk_size:(i+1)*chunk_size] for i in range(num_chunks)]

# 6. RUN THE LLAMA EMBEDDING EXTRACTION
output_dir = f"llama_embeddings_output_ds_name_{ds_name}_{flag_case}"
os.makedirs(output_dir, exist_ok=True)

max_workers = 4
batch_size = 8

if embedding_method.lower() == 'llama3':
    for column in embedding_columns:
        print(f"\nProcessing embeddings for column: {column}")

        # Create combined text
        df[f'combined_{column}'] = df.apply(lambda row: create_combined_text(row, column), axis=1)
        texts = df[f'combined_{column}'].tolist()

        # Break texts into batches
        batches = [texts[i:i + batch_size] for i in range(0, len(texts), batch_size)]

        # Generate embeddings in parallel
        embeddings = []
        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = [executor.submit(get_llama_embeddings, batch) for batch in batches]
            for future in tqdm(concurrent.futures.as_completed(futures),
                               total=len(futures),
                               desc="Generating Llama Embeddings"):
                embeddings.extend(future.result())

        # Prepare the results in a DataFrame
        embedding_df = pd.DataFrame({
            'itemId': df['itemId'],
            'embeddings': embeddings
        })
        embedding_df['embeddings'] = embedding_df['embeddings'].apply(
            lambda x: ' '.join(map(str, x)) if x else ''
        )

        # Shuffle for random distribution
        embedding_df = embedding_df.sample(frac=1, random_state=42).reset_index(drop=True)

        # Split and save
        chunk_size = estimate_chunk_size(embedding_df, sample_size=1000, max_size_mb=25)
        chunks = split_dataframe(embedding_df, chunk_size)

        for idx, chunk in enumerate(chunks):
            output_file = os.path.join(output_dir, f"llama_{column}_part{idx+1}.csv.gz")
            with gzip.open(output_file, 'wt', encoding='utf-8') as f:
                chunk.to_csv(f, index=False)
            print(f"Saved: {output_file}")

    print("\nLlama Embedding Extraction Complete!")

    # Zip and download the folder
    zip_file_name = f"{output_dir}.zip"
    shutil.make_archive(output_dir, 'zip', output_dir)
    files.download(zip_file_name)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.7/69.7 MB 30.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 87.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 85.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 49.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 38.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 90.4 MB/s eta 0:00:00
Dataframe columns: Index(['itemId', 'title', 'genres', 'tag', 'enriched_description', 'pop_class',
       'sim_items_200', 'sim_items_200_class_based',
       'phase1_10p_promote_emotional', 'phase1_10p_promote_neighbor5',
       'phase1_10p_promote_chain5', 'phase1_10p_promote_trigger5',
       'phase1_10p_promote_neighbor15', 'phase1_10p_promote_chain15',
       'phase1_10p_promote_trigger15', 'phase1_40p_promote_emotional',
       'phase1_40p_promote_neighbor5', 'phase1_40p_promote_chain5',
       'phase1_40p_promote_trigger5', 'phase1_40p_promote_neighbor15',
       'phase1_40p_promote_chain15', 'phase1_40p_promote_trigger15',
       'phase1_10p_promote_emotional_semDiff',
       'phase1_10p_promote_neighbor5_semDiff',
       'phase1_10p_promote_chain5_semDiff',
       'phase1_10p_promote_trigger5_semDiff',
       'phase1_10p_promote_neighbor15_semDiff',
       'phase1_10p_promote_chain15_semDiff',
       'phase1_10p_promote_trigger15_semDiff',
       'phase1_40p_promote_emotional_semDiff',
       'phase1_40p_promote_neighbor5_semDiff',
       'phase1_40p_promote_chain5_semDiff',
       'phase1_40p_promote_trigger5_semDiff',
       'phase1_40p_promote_neighbor15_semDiff',
       'phase1_40p_promote_chain15_semDiff',
       'phase1_40p_promote_trigger15_semDiff', 'phase1_promote_applied',
       'final_text_phase1_10p_promote_emotional',
       'final_text_phase1_10p_promote_neighbor5',
       'final_text_phase1_10p_promote_chain5',
       'final_text_phase1_10p_promote_trigger5',
       'final_text_phase1_10p_promote_neighbor15',
       'final_text_phase1_10p_promote_chain15',
       'final_text_phase1_10p_promote_trigger15',
       'final_text_phase1_40p_promote_emotional',
       'final_text_phase1_40p_promote_neighbor5',
       'final_text_phase1_40p_promote_chain5',
       'final_text_phase1_40p_promote_trigger5',
       'final_text_phase1_40p_promote_neighbor15',
       'final_text_phase1_40p_promote_chain15',
       'final_text_phase1_40p_promote_trigger15'],
      dtype='object')

,itemId,title,genres,tag,enriched_description,pop_class,sim_items_200,sim_items_200_class_based,phase1_10p_promote_emotional,phase1_10p_promote_neighbor5,...,final_text_phase1_10p_promote_neighbor15,final_text_phase1_10p_promote_chain15,final_text_phase1_10p_promote_trigger15,final_text_phase1_40p_promote_emotional,final_text_phase1_40p_promote_neighbor5,final_text_phase1_40p_promote_chain5,final_text_phase1_40p_promote_trigger5,final_text_phase1_40p_promote_neighbor15,final_text_phase1_40p_promote_chain15,final_text_phase1_40p_promote_trigger15
0,7,Sabrina (1995),Comedy|Romance,['remake'],**Sabrina (1995)** is a delightful romantic co...,0,"[915, 360, 6899, 345, 2155, 295, 68, 287, 1549...","{0: [186, 500, 555, 597, 1197, 1569, 1777, 229...",NaN,NaN,...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...,**Sabrina (1995)** is a delightful romantic co...
1,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,[],**Money Train (1995)** is a thrilling blend of...,1,"[1604, 5454, 124859, 3537, 2391, 3384, 2344, 4...","{0: [1, 21, 172, 296, 333, 434, 778, 1073, 122...",NaN,NaN,...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...,**Money Train (1995)** is a thrilling blend of...
2,36,Dead Man Walking (1995),Crime|Drama,"['death penalty', 'Nun']",**Dead Man Walking (1995)** is a poignant and ...,0,"[726, 7883, 81, 54787, 4160, 336, 1114, 3258, ...","{0: [151, 253, 282, 288, 377, 587, 1246, 1923,...",NaN,NaN,...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...,**Dead Man Walking (1995)** is a poignant and ...
3,17,Sense and Sensibility (1995),Drama|Romance,['Jane Austen'],**Sense and Sensibility (1995)** is a beautifu...,0,"[7669, 28, 26958, 40629, 70521, 2027, 46976, 1...","{0: [34, 236, 261, 357, 497, 500, 509, 1674, 2...",NaN,NaN,...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...,**Sense and Sensibility (1995)** is a beautifu...
4,3,Grumpier Old Men (1995),Comedy|Romance,"['moldy', 'old']",**Grumpier Old Men (1995)** is a delightful se...,0,"[3450, 1179, 184349, 1929, 100083, 3258, 1473,...","{0: [357, 410, 1278, 1721, 2003, 2324, 2407, 4...",NaN,NaN,...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...,**Grumpier Old Men (1995)** is a delightful se...

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/tokenization_auto.py:823: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/auto_factory.py:471: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Processing embeddings for column: final_text_phase1_10p_promote_emotional

Generating Llama Embeddings: 100%|██████████| 201/201 [01:50<00:00,  1.82it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_emotional_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_emotional_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_emotional_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_emotional_part4.csv.gz

Processing embeddings for column: final_text_phase1_10p_promote_neighbor5

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor5_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor5_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor5_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor5_part4.csv.gz

Processing embeddings for column: final_text_phase1_10p_promote_chain5

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain5_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain5_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain5_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain5_part4.csv.gz

Processing embeddings for column: final_text_phase1_10p_promote_trigger5

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger5_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger5_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger5_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger5_part4.csv.gz

Processing embeddings for column: final_text_phase1_10p_promote_neighbor15

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor15_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor15_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor15_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor15_part4.csv.gz

Processing embeddings for column: final_text_phase1_10p_promote_chain15

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain15_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain15_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain15_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain15_part4.csv.gz

Processing embeddings for column: final_text_phase1_10p_promote_trigger15

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger15_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger15_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger15_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger15_part4.csv.gz

Processing embeddings for column: final_text_phase1_40p_promote_emotional

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_emotional_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_emotional_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_emotional_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_emotional_part4.csv.gz

Processing embeddings for column: final_text_phase1_40p_promote_neighbor5

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor5_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor5_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor5_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor5_part4.csv.gz

Processing embeddings for column: final_text_phase1_40p_promote_chain5

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain5_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain5_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain5_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain5_part4.csv.gz

Processing embeddings for column: final_text_phase1_40p_promote_trigger5

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger5_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger5_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger5_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger5_part4.csv.gz

Processing embeddings for column: final_text_phase1_40p_promote_neighbor15

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part4.csv.gz

Processing embeddings for column: final_text_phase1_40p_promote_chain15

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain15_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain15_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain15_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain15_part4.csv.gz

Processing embeddings for column: final_text_phase1_40p_promote_trigger15

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger15_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger15_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger15_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger15_part4.csv.gz

Processing embeddings for column: enriched_description

Generating Llama Embeddings: 100%|██████████| 201/201 [01:49<00:00,  1.83it/s]

Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_enriched_description_part1.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_enriched_description_part2.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_enriched_description_part3.csv.gz
Saved: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_enriched_description_part4.csv.gz

Llama Embedding Extraction Complete!

In [ ]:
if upload_to_git:
  import os
  import requests
  import base64
  import math



  # Automatically derive the local folder name
  folder_mapping = {
      "OpenAI": f"openai_embeddings_attacked_ds_name_{ds_name}_{flag_case}",
      "sentence_transformer": f"sentence_transformer_embeddings_output_ds_name_{ds_name}_{flag_case}",
      "llama3": f"llama_embeddings_output_ds_name_{ds_name}_{flag_case}",
  }

  local_folder_with_embeddings = folder_mapping.get(embedding_method)
  if not local_folder_with_embeddings:
      raise ValueError(f"Unsupported embedding_method: {embedding_method}")

  # --------------------------------------------------------------------------------
  # 2) Helper function to upload a single file to GitHub
  # --------------------------------------------------------------------------------
  def upload_file_to_github(file_path: str, ds_name: str, token: str):
      """
      Uploads file_path to GitHub repo yasdel/Poison-RAG-Plus under:
        AttackData/Embeddings_from_Augmentation_Attack_Data/<ds_name>/<filename>
      Automatically creates the folder if it doesn't exist.
      Shows read-progress while base64-encoding the file content.
      """

      # Ensure ds_name is valid
      if ds_name not in ["lfm360k", "ml-latest-small"]:
          raise ValueError("ds_name must be either 'lfm360k' or 'ml-latest-small'.")

      # Repo details
      repo_owner = "yasdel"
      repo_name = "Poison-RAG-Plus"
      base_repo_path = "AttackData/Embeddings_from_Augmentation_Attack_Data"

      # Construct final path inside the repo
      github_folder = f"{base_repo_path}/{ds_name}"
      filename_only = os.path.basename(file_path)
      full_path_in_repo = f"{github_folder}/{filename_only}"

      # Read local file in chunks to show progress
      file_size = os.path.getsize(file_path)
      read_bytes = 0
      encoded_bytes = b""

      print(f"Reading file: {file_path} (size: {file_size} bytes)")
      with open(file_path, "rb") as f:
          chunk_size = 1024 * 1024  # 1 MB chunk
          while True:
              chunk = f.read(chunk_size)
              if not chunk:
                  break
              read_bytes += len(chunk)
              encoded_bytes += chunk
              progress_pct = (read_bytes / file_size) * 100
              # Print on the same line with carriage return
              print(f"  Read {read_bytes}/{file_size} bytes ({progress_pct:.2f}%)", end="\r")

      print()  # newline
      print(f"File read completed. Preparing to upload {filename_only} ...")

      # Base64-encode the file content
      encoded_base64 = base64.b64encode(encoded_bytes).decode("utf-8")

      # Build the GitHub API endpoint
      url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/contents/{full_path_in_repo}"

      # Prepare headers and payload for GitHub
      headers = {
          "Authorization": f"token {token}",
          "Accept": "application/vnd.github.v3+json"
      }
      commit_message = f"Upload embeddings file: {filename_only}"
      payload = {
          "message": commit_message,
          "content": encoded_base64,
          "branch": "main"  # adjust this if needed
      }

      # PUT request to create or update the file on GitHub
      response = requests.put(url, headers=headers, json=payload)
      if response.status_code in [200, 201]:
          print(f"SUCCESS: Uploaded {filename_only} to {full_path_in_repo}")
      else:
          print(f"ERROR: Could not upload {filename_only}.")
          print(f"GitHub API response code: {response.status_code}")
          print(f"Response text: {response.text}")

  # --------------------------------------------------------------------------------
  # 3) Main function to upload all *.csv.gz files in local_folder_with_embeddings
  # --------------------------------------------------------------------------------
  def upload_all_embeddings(ds_name: str, token: str, local_folder: str):
      # Ensure local folder exists
      if not os.path.isdir(local_folder):
          raise ValueError(f"Local folder does not exist: {local_folder}")

      # Collect all .csv.gz files
      files_to_upload = [
          os.path.join(local_folder, f)
          for f in os.listdir(local_folder)
          if f.endswith(".csv.gz")
      ]

      if not files_to_upload:
          print(f"No .csv.gz files found in {local_folder}. Nothing to upload.")
          return

      print(f"Found {len(files_to_upload)} .csv.gz files to upload for ds_name={ds_name}.\n")
      for fpath in files_to_upload:
          upload_file_to_github(fpath, ds_name, token)
          print("-" * 80)

  # --------------------------------------------------------------------------------
  # 4) Execute the upload process
  # --------------------------------------------------------------------------------
  upload_all_embeddings(ds_name, my_github_token, local_folder_with_embeddings)

Found 60 .csv.gz files to upload for ds_name=ml-latest-small.

Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor15_part3.csv.gz (size: 5621267 bytes)
  Read 5621267/5621267 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_neighbor15_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_neighbor15_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_neighbor15_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_emotional_part4.csv.gz (size: 3698897 bytes)
  Read 3698897/3698897 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_emotional_part4.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_emotional_part4.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_emotional_part4.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain15_part1.csv.gz (size: 5620173 bytes)
  Read 5620173/5620173 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_chain15_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_chain15_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_chain15_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor15_part4.csv.gz (size: 3697951 bytes)
  Read 3697951/3697951 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_neighbor15_part4.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_neighbor15_part4.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_neighbor15_part4.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor5_part1.csv.gz (size: 5620567 bytes)
  Read 5620567/5620567 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_neighbor5_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_neighbor5_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_neighbor5_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain15_part1.csv.gz (size: 5608358 bytes)
  Read 5608358/5608358 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_chain15_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_chain15_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_chain15_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_emotional_part1.csv.gz (size: 5607532 bytes)
  Read 5607532/5607532 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_emotional_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_emotional_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_emotional_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part4.csv.gz (size: 3698876 bytes)
  Read 3698876/3698876 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_neighbor15_part4.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_neighbor15_part4.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_neighbor15_part4.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain5_part2.csv.gz (size: 5606623 bytes)
  Read 5606623/5606623 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_chain5_part2.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_chain5_part2.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_chain5_part2.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger5_part1.csv.gz (size: 5620002 bytes)
  Read 5620002/5620002 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_trigger5_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_trigger5_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_trigger5_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain5_part4.csv.gz (size: 3699388 bytes)
  Read 3699388/3699388 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_chain5_part4.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_chain5_part4.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_chain5_part4.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_chain15_part3.csv.gz (size: 5620141 bytes)
  Read 5620141/5620141 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_chain15_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_chain15_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_chain15_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor5_part3.csv.gz (size: 5621280 bytes)
  Read 5621280/5621280 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_neighbor5_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_neighbor5_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_neighbor5_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain5_part3.csv.gz (size: 5608273 bytes)
  Read 5608273/5608273 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_chain5_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_chain5_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_chain5_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_emotional_part2.csv.gz (size: 5617584 bytes)
  Read 5617584/5617584 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_emotional_part2.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_emotional_part2.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_emotional_part2.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger15_part4.csv.gz (size: 3737541 bytes)
  Read 3737541/3737541 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_trigger15_part4.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_trigger15_part4.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_trigger15_part4.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain5_part1.csv.gz (size: 5608026 bytes)
  Read 5608026/5608026 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_chain5_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_chain5_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_chain5_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part1.csv.gz (size: 5620027 bytes)
  Read 5620027/5620027 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_neighbor15_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_neighbor15_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_neighbor15_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger15_part4.csv.gz (size: 3699010 bytes)
  Read 3699010/3699010 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_trigger15_part4.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_trigger15_part4.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_trigger15_part4.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_trigger15_part3.csv.gz (size: 5608442 bytes)
  Read 5608442/5608442 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_trigger15_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_trigger15_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_trigger15_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_emotional_part1.csv.gz (size: 5618795 bytes)
  Read 5618795/5618795 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_emotional_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_emotional_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_emotional_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_enriched_description_part2.csv.gz (size: 5618453 bytes)
  Read 5618453/5618453 bytes (100.00%)
File read completed. Preparing to upload llama_enriched_description_part2.csv.gz ...
ERROR: Could not upload llama_enriched_description_part2.csv.gz.
GitHub API response code: 422
Response text: {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents","status":"422"}
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_chain15_part3.csv.gz (size: 5608214 bytes)
  Read 5608214/5608214 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_chain15_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_chain15_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_chain15_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part3.csv.gz (size: 5621548 bytes)
  Read 5621548/5621548 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_neighbor15_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_neighbor15_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_neighbor15_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_neighbor15_part1.csv.gz (size: 5619403 bytes)
  Read 5619403/5619403 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_neighbor15_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_neighbor15_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_neighbor15_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor5_part1.csv.gz (size: 5619879 bytes)
  Read 5619879/5619879 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_neighbor5_part1.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_neighbor5_part1.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_neighbor5_part1.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger5_part2.csv.gz (size: 5618580 bytes)
  Read 5618580/5618580 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_trigger5_part2.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_trigger5_part2.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_trigger5_part2.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_enriched_description_part1.csv.gz (size: 5620007 bytes)
  Read 5620007/5620007 bytes (100.00%)
File read completed. Preparing to upload llama_enriched_description_part1.csv.gz ...
ERROR: Could not upload llama_enriched_description_part1.csv.gz.
GitHub API response code: 422
Response text: {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents","status":"422"}
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor15_part2.csv.gz (size: 5618619 bytes)
  Read 5618619/5618619 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_neighbor15_part2.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_neighbor15_part2.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_neighbor15_part2.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_enriched_description_part3.csv.gz (size: 5620320 bytes)
  Read 5620320/5620320 bytes (100.00%)
File read completed. Preparing to upload llama_enriched_description_part3.csv.gz ...
ERROR: Could not upload llama_enriched_description_part3.csv.gz.
GitHub API response code: 422
Response text: {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents","status":"422"}
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_emotional_part2.csv.gz (size: 5607539 bytes)
  Read 5607539/5607539 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_emotional_part2.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_emotional_part2.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_emotional_part2.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger5_part3.csv.gz (size: 5620118 bytes)
  Read 5620118/5620118 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_trigger5_part3.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_trigger5_part3.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_trigger5_part3.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_40p_promote_neighbor5_part2.csv.gz (size: 5619177 bytes)
  Read 5619177/5619177 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_40p_promote_neighbor5_part2.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_40p_promote_neighbor5_part2.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_40p_promote_neighbor5_part2.csv.gz
--------------------------------------------------------------------------------
Reading file: llama_embeddings_output_ds_name_ml-latest-small_promote/llama_final_text_phase1_10p_promote_trigger5_part4.csv.gz (size: 3699040 bytes)
  Read 3699040/3699040 bytes (100.00%)
File read completed. Preparing to upload llama_final_text_phase1_10p_promote_trigger5_part4.csv.gz ...
SUCCESS: Uploaded llama_final_text_phase1_10p_promote_trigger5_part4.csv.gz to AttackData/Embeddings_from_Augmentation_Attack_Data/ml-latest-small/llama_final_text_phase1_10p_promote_trigger5_part4.csv.gz
--------------------------------------------------------------------------------